title: Edern Le Bot
description: Bookmark this to keep an eye on my project updates!
permalink: /:categories/:title/

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name: "Edern Le Bot"
  #avatar: "/assets/profile.jpg"  # ← put your photo here
  bio: "PhD candidate in Medical Imaging"
  location: "Bordeaux, France"
  employer:
    name: "in2brain @ University of Bordeaux"
    url: "https://in2brain.labri.fr/"
  links: 
    - label: "In2Brain Team @ Université de Bordeaux"
      icon: "fas fa-university"
      url: "https://in2brain.labri.fr/"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=_Lx-WPoAAAAJ"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/elebot4"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/elebot4/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:elebot@u-bordeaux.fr"

# Rendering options

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
