theme: minimal-mistakes-jekyll
title: Edern Le Bot
description: Bookmark this to keep an eye on my project updates!
permalink: /:categories/:title/



author:
  name: "Edern Le Bot"
  #avatar: "/assets/profile.jpg"  # ← put your photo here
  bio: "PhD candidate in Medical Imaging"
  location: "Bordeaux, France"
  employer:
    name: "LaBRI, University of Bordeaux"
    url: "https://in2brain.labri.fr/"
  email: "elebot@u-bordeaux.fr"
  github: "elebot4"
  googlescholar: "https://scholar.google.com/citations?user=_Lx-WPoAAAAJ"
  linkedin: "https://www.linkedin.com/in/elebot4"

# Rendering options

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true

# Staticman
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
